version: '3.1'
services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app
    depends_on:
      - postgres
    networks:
      - fullstack

  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - "./build/postgres.conf:/etc/postgresql/postgresql.conf"
      # - database_postgres:/var/lib/postgresql/data
      - "./build/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    networks:
      - fullstack
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped

volumes:
  api:
  # database_postgres:

networks:
  fullstack:
    driver: bridge
